Update `main.tf`: Add `WEBSITES_PORT` variable; Comment out resource group cleanup in Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -61,18 +61,18 @@ stages:
                 ls -la
                 echo "Initializing Terraform..."
                 terraform init
-
-          - task: AzureCLI@2
-            displayName: 'Clean Resource Group'
-            inputs:
-              connectedServiceNameARM: 'myserviceconnection'
-              scriptType: 'bash'
-              scriptLocation: 'inlineScript'
-              inlineScript: |
-                echo "Cleaning resource group..."
-                az group delete --name $(resource_group_name) --yes --no-wait || echo "Resource group might not exist"
-                echo "Waiting a bit for cleanup..."
-                sleep 100
+#
+#          - task: AzureCLI@2
+#            displayName: 'Clean Resource Group'
+#            inputs:
+#              connectedServiceNameARM: 'myserviceconnection'
+#              scriptType: 'bash'
+#              scriptLocation: 'inlineScript'
+#              inlineScript: |
+#                echo "Cleaning resource group..."
+#                az group delete --name $(resource_group_name) --yes --no-wait || echo "Resource group might not exist"
+#                echo "Waiting a bit for cleanup..."
+#                sleep 100
 
           - task: AzureCLI@2
             displayName: 'Terraform Plan'
